name: Auto Publish Docker Image

on:
  push:
    branches: [main]
    paths:
      - "./**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push metronome
        uses: docker/build-push-action@v3
        with:
          context: metronome
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/metronome:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/metronome:${{ github.sha }}
          build-args: |
            NODE_ENV=production
